[workspace]
resolver = "2"
members = [
    "crates/extt",
    "crates/lib",
]
default-members = ["crates/extt"]

[workspace.package]
publish = false
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.86"
