[package]
name = "extt-settings"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
gpui = { version = "0.2.2", default-features = false }
confy = "0.6"
anyhow = "1.0"
