[package]
name = "extt"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "extt"
path = "src/main.rs"

[dependencies]
lib = { path = "../lib" }
gpui = { git = "https://github.com/zed-industries/zed" }
